[[MMseqs2]]
arch = "aarch64"
git-tree-sha1 = "a15c6e2a809ada57c2dd09df5b1c43e3b9fc73be"
os = "macos"

    [[MMseqs2.download]]
    sha256 = "a50d99519f4b0e3fda60c2f971e98f38e67768aac85cc734428dcde551ba58b7"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.aarch64-apple-darwin.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0de6a1da5bb85057e31d2abe0115e866edf579f"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "f5e6d67526743fb3f90448bb7ab55a470cde6d54b86914010d95b705d1bde153"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80c0bd28c9250b9354b84373ff4e9f666c12f624"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "a6e6760d346d476f33c9899b6f7cf51542ccdc0389f95dfa1cba06585650f94b"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1269b6917c36d53f0145511a948a70bbe99fcebb"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "bb576c6b7d1ffc742acc37490f4803372c0977fdbbb51c493758641aae8cf1bb"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89f0d1e3cd54076c24f7d23d6e42d3b4b67dcd45"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "c97f8fd6199e3c2d3c5814b89a1519d802644b7804062e587a43069dbe267a91"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7640e032b05c30a3ca4723c11ea28d0958b3d13f"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "5f7f491a89ad2b5a6eeac5ff47c73b742846768231fce00d7dd0466497e2bf95"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "630a18a1a919ddd2d59ae4bc136461f1b3bc17b7"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "540f5ee88cf8d4284a3b7358d07343648ddfc7ab03298f390fe6fb0016c032c7"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2aa777a16e6ccf59ec18c0ba1e39c0b7760a47cd"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "862bb57f2dfefc3557cb00cc5fb6a6a44d346704f927ea60ee0c60fcd61301ad"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d3796822b1d74c4876475a781894e682525e5fa"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "976dcc75580e236ad95d9a72eec333f8eae905e7a80568c754bd7cb08e98f0cb"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a3a0eebaa186f94f0dac9f48d72a7374d9559bd"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "dd738f120aba6294746a3fbfc7b843669eca726d8e7aedd989b95958bf7f8072"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76e1e170414bbc73868299d745739e4608593283"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "ea26680feab26c158bb9a97fe2bc95ef2940535beb17b5a4cb7f06f391f908e2"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0935c93872493ef874c06e04cf7573f734783a03"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "129b160532b9ed21195161b62ad2b9f9c0d3cf6d22bdebcb5d11b8d09f957465"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce17151083bf6e51d8c43cdaf5e5865bded3137d"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "973abb98c8160b0628c1cf152e649ec7824a74105c72b96f3be019eeb2f1f93c"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9fee805cc318c554fd1b4b78744b74c63c7b64b"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "f2ca0221071b90edf7f4a3311e0cef205bdf12155db932d23b76b1fe8059d82d"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MMseqs2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea335a6fced47d7b627d60ec68f9d09e0d6a57f8"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "1f7dd941d3f48bb4c126b8e0367895ec26571d2176e7e4e169caa179a5cde081"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b2faebefb1e73ce57cd4ef73f59b113297ecb8a"
os = "macos"

    [[MMseqs2.download]]
    sha256 = "2c1e6a2b0f07ce9d55d73cd54b183807ff04331c810d40e5b3384ca03b7e8d41"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.x86_64-apple-darwin-cxx03.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa0bf192a23e576971b35714fff9ff00c9322798"
os = "macos"

    [[MMseqs2.download]]
    sha256 = "5d9439d06d0aefd76780a4cc5af5d234fb0cf18a3f9d312fc7dd36d4ed57bc15"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.x86_64-apple-darwin-cxx11.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82872dfefc0ec742299ff28cdb7b4ea00e499c32"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "816cabdf10f9951d2d75874f6edcbc6d5c408c2bb1f003d988ec7c76c062e22b"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6d4fcc50b6501e761d72db48ddf47a795c486d0"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "f8dfcf23d06049b2468f88be6220951045fcefc0866963fc38275394c63e3422"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc82df6da7ab56143dce82e67219f025654c59cc"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "c75dba34ad23f60e7392ff932dd9f34483a6f3bc2d5d039f60a3e8797d81e2d3"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cf693b9be4b53110b8e7c75daf73ff8f027a8a4"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "93393763d5181e5c7b22b2510204ee353b21482fdf43f218d2f5a7891fb70b71"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[MMseqs2]]
arch = "x86_64"
git-tree-sha1 = "3ee089bed3b44d6db2de99a55bcba30f8d60a686"
os = "freebsd"

    [[MMseqs2.download]]
    sha256 = "9fbd22ba4421579fa5c7353da32520e10912915720b0a32ef493373f721e458a"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v13.0.0+0/MMseqs2.v13.0.0.x86_64-unknown-freebsd.tar.gz"
