[[MMseqs2]]
arch = "aarch64"
git-tree-sha1 = "9e1952b0b07e9b1d60565020323df94b18ee751a"
os = "macos"

    [[MMseqs2.download]]
    sha256 = "adcd08f447cbe86eb1062529877aaadd81d1cfbf800e4f15535cad0f71b2a9a9"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.aarch64-apple-darwin.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da9ff376310d1a190a427da84a0dec5dffe89048"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "40cfc19b287bb79d4ac29621bc8da103d373c8a5502efc69478b2da2f2bb12f0"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7b2d620b8683ee02373828a7c7fd4725dafe76d"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "f47e797394be8c3de4ce0ce5473770c38a046abad3b07a98a3022546f673f8a5"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33930de768d93cd07e7109cdd933f4b1da6d8b5d"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "d99d8f022b3b720366534f98b821c150799b2fa31a025c3ec1ffbb0d2988f36b"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e06280964be460853ebc362c1ae016f41c1e0452"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "5f321ee29c57939835c719778258b633599108cb388b88eba91aae08e8a1d630"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "391026050cb76e58e618c3eb61a123616134c1ab"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "293b6c9d58dd5fe4b1e362182b2184c27823e1b333843b81a753c1a77ad05753"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb81c6678ee78b3b425f4e87d184c991346f7f09"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "fc6b868d71a2d40f24a12c74a9e9205a070eccc18462efea7513160b6ebfa3ff"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65207402bb74d4f60e465a63f9aadbf42f68eac8"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "2d310b47cd81f3d2a532ee28316461118e34baf8d0daafe1adda0df7ea557e52"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "950e0b16555b6dad5f1640c54f2f542fc7cf0963"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "108df4fa99170087380980e9686408ffbc6bee9dbc72e06c303016437dd815c2"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d2200a82b4c5cde54cc09838e8dd73dfc731de8"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "59bedc0fb2b8033fd434c18badae6fc1d5020e8644c08a23c76df71c3ca396fd"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65579267a190dd75f2cc8e2569103954d8429f97"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "1afac8de1a4d6720a3b3293bf6e0b8bf13525db7c0917c1bf231ec9aa123d167"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18488e283ab3ed2c9ec77b6108dac4b38827c144"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "3bf8c43a70b13491b036dd2803591b8a33c4237b379a958a94b2ac408f708955"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b90d93b80e5b46a2d509fa8d63c2b4840a00eeee"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "9f40358d00805997f82b4ba265bc4dcabd2410301086153474d53290ed272d19"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec42ce13ea63a08360f2aaad99b9ed40c612672d"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "77d802fcfcfaf6a6d4e5abbd080c65ae954e2e2afb4c5c8ed9a24868d8dcb1fb"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MMseqs2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc26b6aeac47ccbceba734e32c3bcb58d8916f2d"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "423f9b7c6cfa2c55c5f407463f7821c5069931e4cd193ddc31f65d0ed555cba1"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MMseqs2]]
arch = "x86_64"
git-tree-sha1 = "f6a6e0ab763abd83802b8e053b1a70068f0b96d4"
os = "macos"

    [[MMseqs2.download]]
    sha256 = "632838a68e590a254303f90112daa3b698645acad4e5146f12dae54830190e7a"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.x86_64-apple-darwin.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9346a572c756d39b7c116de8b2491d3502004b09"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "0c93949373fa1bd0c782df4ea6c349208806537b58871367194e3a2f16350611"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbf41d9c8be52e3ecc5023aeee9c926a21481d91"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "d389ef0fc787f27033313092378ac849fbba5c6db59e1c735cc08bc25c024221"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6298d36086775db5d05e3c5c912b8f2333ef2c11"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "dc70831f433ab46eec944440c65fca42f23c2813f2ec459250d9b3058a23cf18"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "feb2e1095e181a18a58eeebbbf70865c7009cb2b"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "1d979ceb6477f68fca7986b4df8a28929f5fc5cbf711b52db22438333dbf35d7"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[MMseqs2]]
arch = "x86_64"
git-tree-sha1 = "ea4131f00eb959f55fd82f2b54d57de47f34df5e"
os = "freebsd"

    [[MMseqs2.download]]
    sha256 = "cc17c91c74e9f98a572554102f27ac4681a284e04da7978ea323cb9dbb72c63c"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v14.0.0+1/MMseqs2.v14.0.0.x86_64-unknown-freebsd.tar.gz"
