[[MMseqs2]]
arch = "aarch64"
git-tree-sha1 = "38086d1c597d49ab659d8f987988b03e6f336ee3"
os = "macos"

    [[MMseqs2.download]]
    sha256 = "f5e335adcb199e9822668b0eb0c89ed07cc8715efa0782b84f078ed2be417a98"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.aarch64-apple-darwin.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "457e640eb4ea2fa4c4bd114c764c5126304bd099"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "ce6215bfd2573657cb1343d4eda759840965077a6822e0bd2bf40e649f3acfab"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b9a24ed4512a7cd6700daa3ffacf2970ee258b8"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "0be81335f0f4215affea0b6ddbcf1b85848a381e85ce6937026088a88fcbc203"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cd69a7ea9ffc2520de9785226fa319a260f8f10"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "e8fd5350637f80050636d292e5ee731b6b3394d4d1ee6f984adc3d231dd25de4"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[MMseqs2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02cfadaaa2893f7737f6cf01a1c040b8202ae96a"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "153507f7ac8869bb9d9dbc8ac7b3c9f26d79e10d76085c75b97db8ca6b41589e"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d2854251479637614a518451b2005f96498f6e3"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "2e974779a86a40284eb93eaca1475332abb313881c44c39062746fb81b90c529"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "743c148437000ca44b41b98caa66cc27f4136ac9"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "918e468536423e0768cd06c1cec94f96503983eef1c316ddf585412505c28fe1"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03eb6dfb748fb3491f81e7e264e092bf20698d3c"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "8ebef636df568a5f1f87c78fa8c0944daba275e50bd23eecb8c56be15c7178de"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9fbc8a5f3b2248e9c61900a46b1d16b1f966c6c"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "40cbd5c574366ff25373356353280024d2fa17a745e8a18f566f8fa2ba11d9b5"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "865452f973819bdfbee5ee93714fa94a884450aa"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "6debbf4b6b3a5ddfb9d3dfb1bac0d319a3b3980246e13e28480f15cd3d8f76c2"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fce8932acb31cc2b258e5656f96c395552bbb893"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "03dc6c9270ff1db4d6a24288c3f036fe012f7991fa995045cd9ab71b54de485c"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20d630427cbf801255c438fc8fd12355731140c1"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "b39255ec55631b1e00bbea7084987249967472cd95097ac1b33cb38d52fe1e73"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MMseqs2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfd0628eaeef724114999e8ad6c9db38e5116c8a"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "5dc53e10d67e446c04112a9ff3a3ab665e7e704ae70cef414c84dacb65cede04"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MMseqs2]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15583be5329578f7913a6d2cf3ec5be3306856c2"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "d5b175cf24366bfa5fc5bb67e38614c659fe8e3143b239974f3c1eea41821e6c"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MMseqs2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1d2702807a87316c240c80d9e4624eca19c147a"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "efc7257d1c5e297b5686530eb0b4cc66ef496c5ffbc16812aa5f08ff380c6caf"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MMseqs2]]
arch = "x86_64"
git-tree-sha1 = "f5b5ad1c5017eaadab4e2c98de61c5ce1af78952"
os = "macos"

    [[MMseqs2.download]]
    sha256 = "b12eae74f350352c06cdab094f2f23433a769b7a89c8ce150c385ac03c326a4e"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.x86_64-apple-darwin.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "916968c14c6e9155ad5f8e53f8a90b272ee86ae7"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "5b23242b600ae3ddd202a9b5351232e2f5d51d4720f61ed23b830a9d1f2be17d"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88180795328691b89ed93e0e3c3de56307640108"
libc = "glibc"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "fe34dfad3670ee9ee9a2c28c13fa43ca8db980cb255824eec462f3480368a280"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8de39a97d77fbd82c6ae8cc1d494ada8a4a60d6b"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "652a9f7bb893f0969121310b64441978a5d5fd7649f30070565270b1fc3a8ac2"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[MMseqs2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef06dc7103c9bf9cdb9a961a3cae8cefdc4e2ef1"
libc = "musl"
os = "linux"

    [[MMseqs2.download]]
    sha256 = "9eb0b5c1f5bcc152063cd06d7493d826bb49aeaf97031569fd17f1c33f1e9a63"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[MMseqs2]]
arch = "x86_64"
git-tree-sha1 = "0bc6c662edc953f94ca81b14d8a56c59c8b7d324"
os = "freebsd"

    [[MMseqs2.download]]
    sha256 = "501a527651f685f98800149433a1f273248125222bfab688e64f1e55636b56db"
    url = "https://github.com/JuliaBinaryWrappers/MMseqs2_jll.jl/releases/download/MMseqs2-v15.0.0+0/MMseqs2.v15.0.0.x86_64-unknown-freebsd.tar.gz"
