# Autogenerated wrapper script for MMseqs2_jll for x86_64-apple-darwin-cxx11
export mmseqs

using Zlib_jll
using Bzip2_jll
using CompilerSupportLibraries_jll
using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("MMseqs2")
JLLWrappers.@declare_executable_product(mmseqs)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, Bzip2_jll, CompilerSupportLibraries_jll, LLVMOpenMP_jll)
    JLLWrappers.@init_executable_product(
        mmseqs,
        "bin/mmseqs",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
